name: nexus node 1 (CLI)

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 */6 * * *"   # lệch phút giữa các file

concurrency:
  group: nexus-node-1        # <= Đổi khác nhau cho file 2,3
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  run-node:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    env:
      DATA_DIR: nexus_data_node1      # <= Đổi cho file 2,3 để cache tách biệt
      BACKUP_NAME: node1_state_${{ github.run_id }}.tar.zst

    steps:
      - uses: actions/checkout@v4

      - name: Provision 12G swap
        run: |
          sudo fallocate -l 12G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          echo 10 | sudo tee /proc/sys/vm/swappiness

      - name: Restore cache
        id: cache_restore
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.DATA_DIR }}
          key: node1-state-cli-v1-${{ runner.os }}-${{ github.ref_name }}
          restore-keys: |
            node1-state-cli-v1-${{ runner.os }}-
            node1-state-cli-v1-

      - name: Ensure data dir
        run: mkdir -p "${{ env.DATA_DIR }}"

      - name: Install Nexus CLI
        run: |
          set -eux
          curl -sSfL https://cli.nexus.xyz/ | sh
          echo "${HOME}/.nexus/bin" >> $GITHUB_PATH

      - name: Detect Nexus CLI
        run: |
          set -eux
          BIN1="${HOME}/.nexus/bin/nexus-network"
          BIN2="${HOME}/.nexus/bin/nexus"
          if [ -x "$BIN1" ]; then echo "BIN=$BIN1" >> $GITHUB_ENV
          elif [ -x "$BIN2" ]; then echo "BIN=$BIN2" >> $GITHUB_ENV
          else echo "No CLI"; ls -la ~/.nexus/bin || true; exit 1; fi

      - name: Prime state from cache
        run: |
          mkdir -p "${HOME}/.nexus"
          rsync -a "${GITHUB_WORKSPACE}/${{ env.DATA_DIR }}/" "${HOME}/.nexus/" || true

      - name: Start Nexus node (~5h55m) headless
        env:
          NODE_ID: ${{ secrets.NODE_ID_1 }}   # <= File 2 dùng NODE_ID_2, file 3 dùng NODE_ID_3
          TERM: xterm-256color
        run: |
          set -eux
          "${BIN}" --version || true
          "${BIN}" start --help || true
          if "${BIN}" start --help | grep -q -- '--no-tui'; then
            CMD="${BIN} start --node-id ${NODE_ID} --no-tui"
          elif "${BIN}" start --help | grep -qi -- '--daemon'; then
            CMD="${BIN} start --node-id ${NODE_ID} --daemon"
          else
            sudo apt-get update -y
            sudo apt-get install -y util-linux
            CMD="script -q -e -c '${BIN} start --node-id ${NODE_ID}' /dev/null"
          fi
          timeout 21300 bash -lc "$CMD" 2>&1 | tee -a nexus.log || true

      - name: Sync back state
        if: always()
        run: |
          rsync -a --delete "${HOME}/.nexus/" "${GITHUB_WORKSPACE}/${{ env.DATA_DIR }}/" || true

      - name: Upload node log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: nexus-node1.log
          path: nexus.log
          retention-days: 7

      - name: Compress state
        if: always()
        run: |
          sudo apt-get update -y && sudo apt-get install -y zstd
          tar -I "zstd -19" -cf "/tmp/${{ env.BACKUP_NAME }}" -C "${GITHUB_WORKSPACE}" "${{ env.DATA_DIR }}"

      - name: Upload state artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BACKUP_NAME }}
          path: /tmp/${{ env.BACKUP_NAME }}
          retention-days: 7

      - name: Save cache (best-effort)
        if: always()
        continue-on-error: true
        uses: actions/cache/save@v4
        with:
          path: ${{ env.DATA_DIR }}
          key: node1-state-cli-v1-${{ runner.os }}-${{ github.ref_name }}-${{ github.run_id }}-${{ github.run_attempt }}
